---
title: "R Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
install.packages('tidyverse')
install.packages('pander')
install.packages('ggplot2')
library(tidyverse)
library(pander)
library(ggplot2)
```

```{r}
plot(womendata$perc_women,womendata$age)

```
 

```{r, eval=TRUE}
link='https://github.com/lmchu1/WomenLeaders599/raw/master/preprocessed_data.csv'

womendata=read.csv(link,stringsAsFactors = F)

names(womendata)

```



```{r, eval=TRUE}
(summary(womendata)) 

```


```{r, eval=TRUE}
hist(womendata$perc_women,
     xlab= 'Percentage of Female elected representatives' , ylab='Number of Survey Respondents',
     main='Female Representatives among survey respondents',
       col='coral1'
     )

```

```{r}
ggplot(womendata, aes(opinion_leaders))+
       geom_bar(fill='steelblue') + theme_classic() +
  xlab('Opinion about Political Leaders') + ylab('Frequency') + ggtitle('Distribution of Opinions about Leaders')

```

* Collinearity test
```{r}
Linreg=lm(opinion_leaders ~ perc_women + age + hhincome + gender + educ + race + employment + party, data=womendata) 


```

** Explain why this model is not appropriate for our data
```{r}

summary(Linreg)


```

* Multi-collinearity * Ask
```{r}
install.packages('car')
library('car')
vif(Linreg) > 3 

```


```{r}

```

```{r}
#womendata.lm=lm(opinion_leaders~perc_women, data=womendata)
#womendata.res = resid(womendata.lm)
# normality of residuals?
#install.packages("car")
library(car)
qqPlot(womendata.lm, main="QQ Plot")

```

```{r}
library("oglmx")
results.oprob<-oglmx(opinion_leaders ~ perc_women + educ + age + gender + hhincome + employment + party, data=womendata, link="probit",
     constantMEAN = FALSE, constantSD = FALSE,                         
     delta=0,threshparam = NULL)

summary(results.oprob)
                     
```

```{r}
margins.oglmx(results.oprob,ascontinuous = TRUE)
```


Hetero
```{r}
results.oprobhet<-oglmx(opinion_leaders ~ perc_women + educ + age + gender + hhincome + employment + party,~ perc_women + educ + age + gender + hhincome + employment + party, data=womendata,+   
                constantMEAN <- FALSE, constantSD= FALSE)   

summary(results.oprobhet)
```
```{r}

```

